/***********************************************************
 * This software is part of the ProM package * http://www.processmining.org/ * *
 * Copyright (c) 2003-2006 TU/e Eindhoven * and is licensed under the * Common
 * Public License, Version 1.0 * by Eindhoven University of Technology *
 * Department of Information Systems * http://is.tm.tue.nl * *
 **********************************************************/

/* Generated By:JavaCC: Do not edit this line. TpnParserConstants.java */
package org.processmining.plugins.petrinet.importing.tpn;

public interface TpnParserConstants {

	int EOF = 0;
	int NAME = 9;
	int NUMBER = 10;
	int EXPONENT = 11;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\"place\"", "\"trans\"", "\"init\"", "\"inf\"", "\"in\"", "\"out\"", "\"~\"",
			"\";\"", "<NAME>", "<NUMBER>", "<EXPONENT>", "\" \"", "<token of kind 13>", "<token of kind 14>", };

}
